(QC-257) Account Registration Frontend Refactor
query-crew/titanium-banking pull request #36
Opened 2022-08-23 23:05 UTC by jabbott-smoothstack

- Account Registration Frontend is refactored
- Account Type list populated from backend, users select from dropdown menu
- Account information is populated when the user selects an account type from the dropdown menu
- Users can enter an initial deposit
- When the user clicks "Register", they are redirected to an AccountRegistrationSuccess page, which includes a button to redirect them to the home page.

2022-08-24 17:08 UTC, chloejohnsonsmoothstack requested changes
Where's Stripe? The initial deposit account dto accepts a paymentMethodId. I don't see it here.

2022-08-24 18:23 UTC, jabbott-smoothstack commented
> Where's Stripe? The initial deposit account dto accepts a paymentMethodId. I don't see it here.

The Account backend service layer doesn't appear to contain a method for creating a PaymentMethod object, which would have a valid paymentMethodId. Using a placeholder value should always throw a PaymentFailedException, and the account creation would fail as a result. Retrieving a PaymentMethod from the Stripe API would require either a customerId or the paymentMethodId itself, neither of which are available. There's also the possibility that a user would want to transfer funds from an existing account to fund the new account, which wouldn't use Stripe, and should just use the Transactions microservice instead. As a result, I simply used the endpoint that creates the Account via the AccountDto in order to create the account.

I can add a form to allow the user to select their method of account funding, including a form to use Stripe payments, but it doesn't seem like it would be usable or testable at the moment.

2022-08-25 17:43 UTC, chloejohnsonsmoothstack approved these changes

2022-08-25 19:07 UTC, alexdongss approved these changes

2022-08-25 19:12 UTC, merged